### ISSUE TITLE
libsbgnpy with Python 3

### ISSUE THREAD

**Issue by annazhukova** [matthiaskoenig/libsbgn-python#4]
Hi Matthias,

I am trying to switch to Python 3.5.1 from Python 2.7.11 (where libsbgn-python worked perfectly) and having some troubles:

```
...
    from libsbgnpy import libsbgn
  File "/usr/local/lib/python3.5/dist-packages/libsbgnpy/__init__.py", line 4, in <module>
    from _version import __version__
ImportError: No module named '_version'
```

It seems to be sort of a relative path issue as if I change inside "/usr/local/lib/python3.5/dist-packages/libsbgnpy/__init__.py":
`from _version import __version__` to `from ._version import __version__` this issue disappears. However then it starts complaining about not finding libsbgnTypes (that are present inside my /usr/local/lib/python3.5/dist-packages/libsbgnpy/ folder).

Thanks,
Anna

**Comment by iseekwonderful** [comment]
Hello, I use libsbgnpy at python 3.5.1 too.
seems change `from libsbgnTypes import Language, GlyphClass, ArcClass, Orientation` to
`from .libsbgnTypes import Language, GlyphClass, ArcClass, Orientation` could solve this problems

I hope Matthias could migrate this lib to py3

Thank you!

**Comment by matthiaskoenig** [comment]
Hi @annazhukova and @iseekwonderful,
I will take care of the py3 support in the next few days. 
If it is really only the relative imports this will be a quick fix.

I have to setup some continouus integration so I can check that it works under py2 and py3, but should not be too much work.

Thanks for the report.
M

**Comment by matthiaskoenig** [comment]
This works in in the develop branch now.
All unittests successful on py2.6, py2.7, py3.4, py3.5 and py3 nightly.
https://travis-ci.org/matthiaskoenig/libsbgn-python

I will make a new release now on master. From now on official support on py2 and py3.

**Comment by matthiaskoenig** [comment]
Closing this now. This should work with latest release v0.1.4.
If you have any issues just reopen this issue.

Thanks @annazhukova and @iseekwonderful for the great issue report.

**Comment by annazhukova** [comment]
Hi @matthiaskoenig,

Thanks for fixing this so quickly.
However, I have another problem now, in your libsbgn.py/quote_attrib(isStr) method:

`NameError: name 'basestring' is not defined
`

As you can see [here](https://docs.python.org/3.0/whatsnew/3.0.html#text-vs-data-instead-of-unicode-vs-8-bit) they've removed the basestring in Python3 and suggest using str instead:

> The builtin basestring abstract type was removed. Use str instead. The str and bytes types don’t have functionality enough in common to warrant a shared base class. The 2to3 tool (see below) replaces every occurrence of basestring with str.

**Comment by matthiaskoenig** [comment]
I will fix this as soon as possible.

Notes to self: Necessary to check the full code base for py3 issues
* look into py2 to py3 conversion tools (code checker)
* probably necessary to recreate from xml with a py3 aware tool (see #1)

**Comment by matthiaskoenig** [comment]
@annazhukova 
If you have some minimal code example which shows the issue please post here, than I can use this for testing.

**Comment by annazhukova** [comment]
Here you go:

```
from libsbgnpy import libsbgn
from libsbgnpy.libsbgnTypes import Language, GlyphClass, ArcClass

if "__main__" == __name__:
    # create empty sbgn
    sbgn = libsbgn.sbgn()

    # create map, set language and set in sbgn
    sbgn_map = libsbgn.map()
    sbgn_map.set_language(Language.PD)
    sbgn.set_map(sbgn_map)

    # create a bounding box for the map
    box = libsbgn.bbox(0, 0, 100, 100)
    sbgn_map.set_bbox(box)

    # glyphs with labels
    for comp in ('Cytoplasm', ):
        c_id = comp
        c_name = comp
        (x, y), (w, h) = (10, 10), (90, 90)
        g = libsbgn.glyph(class_=GlyphClass.COMPARTMENT, id=c_id)
        g.set_label(libsbgn.label(text=c_name, bbox=libsbgn.bbox(x, y, w, h)))
        g.set_bbox(libsbgn.bbox(x, y, w, h))
        sbgn_map.add_glyph(g)

    s2xy = {'H2': (20, 20), 'O2': (20, 80), 'H2O': (80, 60)}
    for species, (x, y) in s2xy.items():
        s_id = species
        s_name = species
        glyph_type = GlyphClass.UNSPECIFIED_ENTITY
        glyph_type = GlyphClass.SIMPLE_CHEMICAL

        (w, h) = (5, 5)
        g = libsbgn.glyph(class_=glyph_type, id=s_id, compartmentRef='Cytoplasm')
        g.set_label(libsbgn.label(text=s_name,
                                  bbox=libsbgn.bbox(x + w * 0.1, y + h * 0.1, w * 0.8, h * 0.8)))
        g.set_bbox(libsbgn.bbox(x, y, w, h))
        sbgn_map.add_glyph(g)

    # glyph with ports (process)
    r_id = 'Water'
    (x, y), (w, h) = (60, 60), (4, 4)
    g = libsbgn.glyph(class_=GlyphClass.PROCESS, id=r_id)
    g.set_bbox(libsbgn.bbox(x, y, w, h))

    in_port = None
    for s_id in ('O2', 'H2'):
        edge_id = "-".join(sorted((s_id, r_id)))

        if not in_port:
            port_x, port_y = (61, 62)
            in_port = libsbgn.port(x=port_x, y=port_y, id="%s__in" % r_id)
            g.add_port(in_port)

        sref_id = s_id
        a = libsbgn.arc(class_=ArcClass.CONSUMPTION,
                        target=in_port.get_id(),
                        source=sref_id, id="a_%s_%s" % (s_id, r_id))
        s_x, s_y = s2xy[s_id]
        a.set_start(libsbgn.startType(x=s_x, y=s_y))
        a.set_end(libsbgn.endType(x=in_port.get_x(), y=in_port.get_y()))
        sbgn_map.add_arc(a)
    out_port = None
    for s_id in ('H2O', ):
        edge_id = "-".join(sorted((s_id, r_id)))

        if not out_port:
            port_x, port_y = (63, 62)
            out_port = libsbgn.port(x=port_x, y=port_y, id="%s__out" % r_id)
            g.add_port(out_port)
        sref_id = s_id
        a = libsbgn.arc(class_=ArcClass.PRODUCTION, target=sref_id, source=out_port.get_id(),
                        id="a_%s_%s" % (r_id, s_id))
        s_x, s_y = s2xy[s_id]
        a.set_end(libsbgn.startType(x=s_x, y=s_y))
        a.set_start(libsbgn.endType(x=out_port.get_x(), y=out_port.get_y()))
        sbgn_map.add_arc(a)
    sbgn_map.add_glyph(g)

    # write everything to a file
    sbgn.write_file('./test.sbgn')
```

**Comment by matthiaskoenig** [comment]
@annazhukova Is fixed now in develop branch.
Could you check if everything works for you now, than I make a bugfix release.

**Comment by annazhukova** [comment]
Hello @matthiaskoenig,

I can run the scripts with no problem now, but the result produced is not a valid sbgn: I try to open the file produced with the code that I posted before with [SBMLLayout Viewer](http://sysbioapps.dyndns.org/Layout/) and it complains:
```
Error

'b' is an unexpected token. The expected token is '"' or '''. Line 2, position 65.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(Stream inStream)
   at SBMLExtension.Util.readLayout(String sXML, Boolean overWriteWithSBGNDefault)
   at Welcome.Controllers.LayoutController.UpdateImage(String file, Boolean sbgn)
If this problem persists, please notify the author.
```

When I look inside the sbgn file, I see that all the attribute values are surrounded with b'', e.g. ` id=b'"O2"'`.

**Comment by iseekwonderful** [comment]
This occurs when a `byte` is converted to a `str` use `str()` method,  use `decode` could solve this problem

**Comment by matthiaskoenig** [comment]
@annazhukova 
Will fix this tonight. 
Have to write some unittests to check this (roundtrip writing and reading) and probably implement validation of SBGN files in the process (see #7)

**Comment by matthiaskoenig** [comment]
@annazhukova 
This should be fixed now.
I could load the created files without problems in
- SBGN-ED
- SBML layout viewer (http://sysbioapps.dyndns.org/Layout/)
- Chise.js (http://www.cs.bilkent.edu.tr/%7Eivis/ChiSE.js/sample-app/#)
Created with py2 and py3.

To fix this I had to recreate the language bindings with some py2/py3 aware schema parser. The code passes all unit tests, but you should check if everything works with your production code. There could be some subtle changes I do not cover with unittests.

**Comment by annazhukova** [comment]
Thanks a lot @matthiaskoenig !
