### ISSUE TITLE
Suggest to add auto-layout function

### ISSUE THREAD

**Issue by weiheng-liao** [matthiaskoenig/libsbgn-python#44]
I tried to create a new sbgn using libsbgnpy, but I have to define the position of each node, which is too bad. T 0 T

**Comment by cannin** [comment]
@henry-leo See the syblars_example Python code to help you auto-layout the networks: https://gist.github.com/cannin/7e35f3fae274370bd0a70c7b1840c743 

syblars: https://github.com/iVis-at-Bilkent/syblars

**Comment by weiheng-liao** [comment]
> @henry-leo See the syblars_example Python code to help you auto-layout the networks: https://gist.github.com/cannin/7e35f3fae274370bd0a70c7b1840c743
> 
> syblars: https://github.com/iVis-at-Bilkent/syblars

That is wonderful! THANKS
